import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      "colors": {
        "on-tertiary-container": "#626161",
        "primary": "#efffe3",
        "on-secondary-fixed-variant": "#614000",
        "on-primary-fixed": "#022100",
        "on-tertiary-fixed": "#1c1b1b",
        "on-surface-variant": "#baccb0",
        "on-surface": "#e5e2e1",
        "inverse-primary": "#106e00",
        "secondary-container": "#fdaf00",
        "on-primary": "#053900",
        "inverse-on-surface": "#313030",
        "on-error-container": "#ffdad6",
        "tertiary": "#fdf9f9",
        "outline": "#85967c",
        "toxic-glow": "rgba(57, 255, 20, 0.15)",
        "tertiary-fixed": "#e5e2e1",
        "on-background": "#e5e2e1",
        "terminal-green-dim": "#1E4D12",
        "primary-fixed": "#79ff5b",
        "text-muted": "#888888",
        "on-tertiary-fixed-variant": "#474746",
        "surface-container-high": "#2a2a2a",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#107100",
        "surface-container-low": "#1c1b1b",
        "background": "#131313",
        "on-secondary-fixed": "#281800",
        "tertiary-container": "#e0dddc",
        "on-primary-fixed-variant": "#095300",
        "secondary-fixed": "#ffddaf",
        "secondary-fixed-dim": "#ffba43",
        "amber-glow": "rgba(255, 176, 0, 0.2)",
        "surface-container": "#201f1f",
        "on-error": "#690005",
        "primary-fixed-dim": "#2ae500",
        "secondary": "#ffd393",
        "error": "#ffb4ab",
        "surface-dim": "#131313",
        "surface-variant": "#353534",
        "surface-container-highest": "#353534",
        "surface-bright": "#3a3939",
        "on-tertiary": "#313030",
        "tertiary-fixed-dim": "#c8c6c5",
        "primary-container": "#39ff14",
        "border-subtle": "#222222",
        "on-secondary-container": "#694600",
        "on-secondary": "#432c00",
        "surface": "#131313",
        "outline-variant": "#3c4b35",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "surface-tint": "#2ae500"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-sm": "8px",
        "unit": "4px",
        "panel-padding": "12px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "16px",
        "margin-page": "24px"
      },
      "fontFamily": {
        "headline-sm": ["Hanken Grotesk"],
        "body-sm": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "body-lg": ["JetBrains Mono"],
        "headline-lg": ["Hanken Grotesk"],
        "mono-data": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "body-md": ["JetBrains Mono"]
      },
      "fontSize": {
        "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "body-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}],
        "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "mono-data": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
};

export default config;
