import type { NarrativeTemplate } from './NarrativeCombatTypes';

export const NARRATIVE_TEMPLATE_POOL: NarrativeTemplate[] = [
  {
    id: 'opening_dark_01',
    type: 'opening',
    weight: 10,
    text: '{targetName} hien than trong {battlefieldName}. Uy ap canh gioi bat dau de nang len than hon.',
  },
  {
    id: 'choice_quiet_01',
    type: 'choice',
    phase: ['probing', 'pressure'],
    weight: 8,
    text: '{actorName} lua chon: {choiceText}',
  },
  {
    id: 'cast_sword_probing_01',
    type: 'cast',
    phase: ['probing'],
    tags: ['sword'],
    weight: 10,
    text: '{actorName} thu kiem nhu tham do sau nong cua {targetName}.',
  },
  {
    id: 'cast_sword_pressure_01',
    type: 'cast',
    phase: ['pressure', 'dominance'],
    tags: ['sword', 'momentum'],
    weight: 8,
    conditions: { momentumOwner: 'actor' },
    text: 'Kiem the cua {actorName} lien mien khong dut, ep {targetName} lui nua buoc.',
  },
  {
    id: 'cast_flame_climax_01',
    type: 'cast',
    phase: ['desperation', 'climax'],
    tags: ['flame'],
    weight: 7,
    conditions: { minTension: 60 },
    text: '{actorName} dot linh luc, xich viem day troi nhu muon thieu rung ao canh.',
  },
  {
    id: 'cast_lotus_calm_01',
    type: 'cast',
    tags: ['lotus', 'calm'],
    weight: 8,
    text: '{actorName} giu tam nhu mat nuoc; trong sat khi van no ra mot canh sen lanh.',
  },
  {
    id: 'cast_demonic_01',
    type: 'cast',
    tags: ['demonic'],
    weight: 9,
    text: '{actorName} khong buoc toi, nhung bong toi duoi chan da bo qua {targetName}.',
  },
  {
    id: 'damage_light_01',
    type: 'damage',
    weight: 10,
    text: 'Du am cua don danh luot qua ho the chan khi cua {targetName}.',
  },
  {
    id: 'damage_heavy_01',
    type: 'damage',
    weight: 8,
    conditions: { minAmount: 30 },
    text: '{targetName} rung minh, khi huyet dao lon sau mot kich cua {actorName}.',
  },
  {
    id: 'damage_repeated_01',
    type: 'damage',
    weight: 7,
    conditions: { repeatedActionAtLeast: 3 },
    text: 'Vet thuong cu chua khep lai da bi cung mot dao y xuyen qua lan nua.',
  },
  {
    id: 'heal_lotus_01',
    type: 'heal',
    tags: ['lotus'],
    weight: 8,
    text: 'Mot hoi thanh khi cham rai keo {actorName} ra khoi mieng vuc.',
  },
  {
    id: 'resource_qi_01',
    type: 'resource',
    tags: ['resource'],
    weight: 7,
    text: 'Khi mach cua {actorName} sang len mot sat na, roi lai chim vao im lang.',
  },
  {
    id: 'reaction_fear_01',
    type: 'fear',
    tags: ['fear'],
    weight: 7,
    conditions: { targetFearAbove: 45 },
    text: 'Trong mat {targetName} thoang qua mot tia so hai rat mong.',
  },
  {
    id: 'reaction_instability_01',
    type: 'dao_instability',
    tags: ['instability'],
    weight: 7,
    conditions: { actorComposureBelow: 55 },
    text: 'Dao tam cua {targetName} xao dong; linh dai hien len mot vet nut vo hinh.',
  },
  {
    id: 'suppression_pressure_01',
    type: 'suppression',
    phase: ['pressure', 'dominance'],
    tags: ['suppression'],
    weight: 8,
    conditions: { minTension: 35, momentumOwner: 'actor' },
    text: 'Uy ap cua {actorName} dang de nang len linh dai {targetName}.',
  },
  {
    id: 'battlefield_pressure_01',
    type: 'battlefield_pressure',
    phase: ['pressure'],
    tags: ['dao_pressure'],
    weight: 9,
    text: 'Tam Ma Ao Canh bat dau rung dong duoi sat khi hai ben.',
  },
  {
    id: 'intent_growth_sword_01',
    type: 'intent_growth',
    tags: ['sword'],
    weight: 7,
    conditions: { repeatedActionAtLeast: 2 },
    text: 'Moi duong kiem cua {actorName} deu nhanh hon truoc.',
  },
  {
    id: 'climax_spiritual_collapse_01',
    type: 'spiritual_collapse',
    phase: ['climax'],
    weight: 10,
    text: 'Sinh tu chi cach mot niem. Ngay ca linh khi cung khong dam luu dong.',
  },
  {
    id: 'atmosphere_distortion_01',
    type: 'atmosphere_distortion',
    phase: ['dominance', 'climax'],
    tags: ['spatial'],
    weight: 5,
    conditions: { minTension: 70 },
    text: 'Khong gian quanh hai ben vo nhe thanh nhung duong nut den tham.',
  },
  {
    id: 'rare_enlightenment_01',
    type: 'enlightenment',
    phase: ['desperation', 'climax'],
    tags: ['enlightenment'],
    weight: 2,
    conditions: { minTension: 65, rareChance: 0.035 },
    text: 'Trong khe ho giua sinh va tu, {actorName} bong nhin thay mot duong phap chua tung ton tai.',
  },
  {
    id: 'rare_heart_demon_01',
    type: 'heart_demon',
    phase: ['desperation', 'climax'],
    tags: ['heart_demon'],
    weight: 2,
    conditions: { minTension: 70, rareChance: 0.03 },
    text: 'Sau lung {targetName}, mot bong den co cung khuon mat cham rai mo mat.',
  },
  {
    id: 'result_player_01',
    type: 'result',
    weight: 10,
    text: '{targetName} tan ra nhu muc roi vao nuoc. Mot chuong chien dau khep lai.',
  },
  {
    id: 'result_enemy_01',
    type: 'result',
    weight: 10,
    text: '{actorName} guc xuong. Tam Ma Ao Canh chim vao tinh lang lanh le.',
  },
];
